
import "./globals.css";


export const metadata = {
  title: "Formações BEI Educação",
  description: "Generated by Hélio Sales Jr.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
